version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/mono/served/professionals/amy/certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /home/mono/served/professionals/amy/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80  # Corrected port
    depends_on:
      - nginx-proxy

volumes:
  vhostd:
  certs:
  html:
  acme:
